import { NextResponse } from 'next/server';
import { LogEntry, PaginatedLogs } from '@/types/log';

// Generate some mock data
const generateMockLogs = (count: number): LogEntry[] => {
  return Array.from({ length: count }).map((_, i) => ({
    id: `log-${i + 1}`,
    startTime: new Date(Date.now() - i * 1000 * 60 * 60).toISOString().slice(0, 16).replace('T', ' '),
    status: Math.random() > 0.2 ? 'SUCCESS' : Math.random() > 0.5 ? 'FAILURE' : 'PARTIAL_SUCCESS',
    runTime: Number((Math.random() * 5 + 1).toFixed(3)),
    tokens: Math.floor(Math.random() * 2000) + 100,
    input: {
      "sys.query": "What does this photograph express?",
      "sys.files": [
        {
          "type": "image",
          "url": "https://example.com/image.jpg"
        }
      ]
    },
    output: {
      "output": "This is a mock response generated by the system.",
      "raw_output": "This is a mock response generated by the system."
    }
  }));
};

const MOCK_DB = generateMockLogs(50);

export async function GET(request: Request) {
  const { searchParams } = new URL(request.url);
  const page = parseInt(searchParams.get('page') || '1');
  const pageSize = parseInt(searchParams.get('pageSize') || '20');
  const status = searchParams.get('status');
  const search = searchParams.get('search');

  let filteredLogs = [...MOCK_DB];

  if (status && status !== 'All') {
    filteredLogs = filteredLogs.filter(log => log.status === status);
  }

  if (search) {
    const searchLower = search.toLowerCase();
    filteredLogs = filteredLogs.filter(log =>
      log.id.toLowerCase().includes(searchLower) ||
      JSON.stringify(log.input).toLowerCase().includes(searchLower) ||
      JSON.stringify(log.output).toLowerCase().includes(searchLower)
    );
  }

  const total = filteredLogs.length;
  const start = (page - 1) * pageSize;
  const end = start + pageSize;
  const data = filteredLogs.slice(start, end);

  const response: PaginatedLogs = {
    data,
    total,
    page,
    pageSize,
  };

  return NextResponse.json(response);
}
